# Generated by Django 2.1.1 on 2018-09-06 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notekeep', '0003_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='tags',
            field=models.ManyToManyField(to='notekeep.Tag'),
        ),
    ]
